[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
evm_version = "london"

[lint]
lint_on_build = false
[profile.compiler]
optimizer = true
runs = 200  # 设置优化的运行次数
viaIR = true 


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
